name: test
on: [push]
jobs:
  test_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: run tests
      run: |
        pip install pytest
        pytest    

    - name: build docker image
      run: 
        docker build -t test_functions .  

    - name: run docker image
      run: 
        docker run test_function
        
    - name: push docker image
      run: 
        echo "${{ secrets.HEMA }}" | docker login -u "ibrahimbadr" --password-stdin
        docker push ibrahimbadr
        