name: test
on: [push]
jobs:
  test_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: run tests
      run:  |
        pip install pytest
        pytest    

    - name: build docker image
      run: 
        docker build -t ibrahimbadr/pytest-http .  

    - name: run docker image
      run: 
        docker run ibrahimbadr/pytest-http

    - name: push docker image
      run:  |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker push ibrahimbadr/pytest-http
